# Copyright Tecnalia Research && Innovation
# All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

version: '3.6'


services:
    #################################### BLOCKCHAIN ####################################

    ethereum:
        image: trufflesuite/ganache-cli:latest
        container_name: ethereum
        command: ./ganache -i=5777
        ports:
            - 8545:8545
        networks:
            marketplace:
                ipv4_address: 192.168.130.2
        
    #################################### IPFS ####################################
    ipfs:
        image: ipfs/go-ipfs:v0.5.1
        container_name: ipfs
        volumes:
            - /opt/volumes/ipfs:/data/ipfs
        healthcheck:
            test: ["CMD-SHELL", "if ! nc -z -v -w5 localhost 5001 &> /dev/null; then exit 1; fi"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - 4001:4001
            - 5001:5001
            - 8080:8080
        depends_on:
            - ethereum
        networks:
            marketplace:
                ipv4_address: 192.168.130.3

    ipfs-cluster:
        image: ipfs/ipfs-cluster:v0.13.0
        container_name: ipfs-cluster
        command: daemon --bootstrap /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWCtt2LAfaQe3hhEABSbUefRUcio6jhXC7VU6aQrkuihu7
        environment:
            CLUSTER_PEERNAME: ipfs-cluster
            CLUSTER_SECRET: 753273fc4e9e0375b3cfdf99f3e72744e6025834a6df6e9eb8ff7e6f3ba9bc34
            CLUSTER_REPLICATIONFACTORMIN: 2
            CLUSTER_REPLICATIONFACTORMAX: 4
            CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
            CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
            CLUSTER_MONITORPINGINTERVAL: 2s
            IPFS_CLUSTER_CONSENSUS: crdt
        volumes:
            - /opt/volumes/ipfs-cluster:/data/ipfs-cluster
        ports:
            - 9094:9094
            - 9095:9095
            - 9096:9096
        depends_on:
            - ethereum
            - ipfs
        networks:
            marketplace:
                ipv4_address: 192.168.130.4
    
    #################################### EVENTEUM ####################################

    eventeum:
        image: eventeum/eventeum:latest
        container_name: eventeum
        ports:
            - 8060:8060
        depends_on:
            - ethereum
            - mongodb
            - kafka
        environment:
            SPRING_DATA_MONGODB_HOST: mongodb
            ETHEREUM_NODE_URL: http://ethereum:8545    # Aqui poner el nodo de ethereum/quorum
            ZOOKEEPER_ADDRESS: zookeper:2181
            KAFKA_ADDRESSES: kafka:19092
            BROADCASTER_TYPE: "KAFKA"
        networks:
            marketplace:
                ipv4_address: 192.168.130.5

    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - 27017:27017
        volumes:
            - ./mongodb/data/mongodb/data/db:/data/db
        networks:
            marketplace:
                ipv4_address: 192.168.130.6

    zookeeper:
        image: confluentinc/cp-zookeeper:5.0.1-1
        container_name: zookeeper
        ports:
            - 2181:2181
        environment:
            zk_id: "1"
            ZOOKEEPER_CLIENT_PORT: 2181
        networks:
            marketplace:
                ipv4_address: 192.168.130.7

    kafka:
        image: confluentinc/cp-kafka:5.0.1-1
        container_name: kafka
        ports:
            - 9092:9092
            - 19092:19092
        depends_on:
            - ethereum
            - zookeeper
        environment:
        # For more details see See https://rmoff.net/2018/08/02/kafka-listeners-explained/
            KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://kafka:9092
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"     
            KAFKA_BROKER_ID: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            marketplace:
                ipv4_address: 192.168.130.8


#################################### CONFIGURATION ####################################

networks:
    marketplace:
        name: marketplace
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.130.1/24