# Copyright Tecnalia Research && Innovation
# All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

version: '3.6'

networks:
  marketplace:
    external: true

x-common-envs: &common-envs
    ETHEREUM_NODE_URL: http://ethereum:8545
    MARKETPLACE: '0x75451f859eE0F8CD299E507a7Cc566692aAD4e69'
    TOKEN: '0x8b013611067770b3f861F742f62Cc8589e0E7509'
    IPFS_GATEWAY: '/ip4/192.168.130.3/tcp/5001/http'
    KEYSTORE: 'keystore/eth/'

services:
  #################################### SCALE-MAMBA ####################################

    p0:
        image: 'agent:latest'
        container_name: p0
        tty: true
        working_dir: /app/client
        ports:
            - 5100-5105:5000-5005
        volumes:
            - './client/data-scientist-eth-client:/app/client'
            - './client/p0:/app/client/Data'
        environment:
            <<: *common-envs
            IP_ADDRESS: '192.168.130.9'
            CA_FILE_LOCATION: './Data/Certificates/RootCA.crt'
            CERT_FILE_LOCATION: './Data/Certificates/player0.crt'
            KEY_FILE_LOCATION: './Data/Certificates/player0.key'
            PROGRAMS_LOCATION: './Data/Programs/'
            MPC_DATA_LOCATION: '/app/MP-SPDZ/'
            INPUT_FILE_LOCATION: './Data/MPC-data/input.txt'
            OUTPUT_FILE_LOCATION: './Data/MPC-data/output.txt'
            COMMON_NAME: 'player0@example.com'
            ACCOUNT_NAME: 'prueba1'
        networks:
            marketplace:
                ipv4_address: 192.168.130.9
        
    p1:
        image: 'agent:latest'
        container_name: p1
        tty: true
        working_dir: /app/client
        ports:
            - 5200-5205:5000-5005
        volumes:
            - './client/data-owner-eth-client:/app/client'
            - './client/p1:/app/client/Data'
        environment:
            <<: *common-envs
            IP_ADDRESS: '192.168.130.10'
            CA_FILE_LOCATION: './Data/Certificates/RootCA.crt'
            CERT_FILE_LOCATION: './Data/Certificates/player1.crt'
            KEY_FILE_LOCATION: './Data/Certificates/player1.key'
            PROGRAMS_LOCATION: './Data/Programs/'
            MPC_DATA_LOCATION: '/app/MP-SPDZ/'
            INPUT_FILE_LOCATION: './Data/MPC-data/input.txt'
            OUTPUT_FILE_LOCATION: './Data/MPC-data/output.txt'
            COMMON_NAME: 'player1@example.com'
            ACCOUNT_NAME: 'prueba2'
        networks:
            marketplace:
                ipv4_address: 192.168.130.10

    p2:
        image: 'agent:latest'
        container_name: p2
        tty: true
        working_dir: /app/client
        ports:
            - 5300-5305:5000-5005
        volumes:
            - './client/data-owner-eth-client:/app/client'
            - './client/p2:/app/client/Data'
        environment:
            <<: *common-envs
            IP_ADDRESS: '192.168.130.11'
            CA_FILE_LOCATION: './Data/Certificates/RootCA.crt'
            CERT_FILE_LOCATION: './Data/Certificates/player2.crt'
            KEY_FILE_LOCATION: './Data/Certificates/player2.key'
            PROGRAMS_LOCATION: './Data/Programs/'
            MPC_DATA_LOCATION: '/app/MP-SPDZ/'
            INPUT_FILE_LOCATION: './Data/MPC-data/input.txt'
            OUTPUT_FILE_LOCATION: './Data/MPC-data/output.txt'
            COMMON_NAME: 'player2@example.com'
            ACCOUNT_NAME: 'prueba3'
        networks:
            marketplace:
                ipv4_address: 192.168.130.11

    p3:
        image: 'agent:latest'
        container_name: p3
        tty: true
        working_dir: /app/client
        ports:
            - 5400-5405:5000-5005
        volumes:
            - './client/data-owner-eth-client:/app/client'
            - './client/p3:/app/client/Data'
        environment:
            <<: *common-envs
            IP_ADDRESS: '192.168.130.12'
            CA_FILE_LOCATION: './Data/Certificates/RootCA.crt'
            CERT_FILE_LOCATION: './Data/Certificates/player3.crt'
            KEY_FILE_LOCATION: './Data/Certificates/player3.key'
            PROGRAMS_LOCATION: './Data/Programs/'
            MPC_DATA_LOCATION: '/app/MP-SPDZ/'
            INPUT_FILE_LOCATION: './Data/MPC-data/input.txt'
            OUTPUT_FILE_LOCATION: './Data/MPC-data/output.txt'
            COMMON_NAME: 'player3@example.com'
            ACCOUNT_NAME: 'prueba4'
        networks:
            marketplace:
                ipv4_address: 192.168.130.12

    p4:
        image: 'agent:latest'
        container_name: p4
        tty: true
        working_dir: /app/client
        ports:
            - 5500-5505:5000-5005
        volumes:
            - './client/data-owner-eth-client:/app/client'
            - './client/p4:/app/client/Data'
        environment:
            <<: *common-envs
            IP_ADDRESS: '192.168.130.13'
            CA_FILE_LOCATION: './Data/Certificates/RootCA.crt'
            CERT_FILE_LOCATION: './Data/Certificates/player4.crt'
            KEY_FILE_LOCATION: './Data/Certificates/player4.key'
            PROGRAMS_LOCATION: './Data/Programs/'
            MPC_DATA_LOCATION: '/app/MP-SPDZ/'
            INPUT_FILE_LOCATION: './Data/MPC-data/input.txt'
            OUTPUT_FILE_LOCATION: './Data/MPC-data/output.txt'
            COMMON_NAME: 'player4@example.com'
            ACCOUNT_NAME: 'prueba5'
        networks:
            marketplace:
                ipv4_address: 192.168.130.13